[build]
  base = "frontend"
  publish = "dist"
  command = "npm install --no-save && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  CI = "true"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
