[build]
  base = "frontend"
  publish = "dist"
  command = "npm install $NPM_FLAGS && npx vite build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
