[build]
  base = "frontend"
  publish = "dist"
  command = "npm install vite@5.0.11 @vitejs/plugin-react --save-dev && npm install $NPM_FLAGS && npx vite build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_SKIP_TS_CHECK = "true"
  VITE_USER_NODE_ENV = "production"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
